name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to Heroku
      uses: actions/heroku@v2
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU_API_KEY }}
    - name: Deploy to Heroku
      uses: actions/heroku@v2
      with:
        app-name: your-heroku-app-name
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        buildpacks: heroku/python
        push-github-commit: true
