name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to Heroku
      uses: actions/heroku@v2
      with:
        email: "guinnessgshep@gmail.com"
        api_key: "c3814a48-7319-4586-ab1d-a6a5bf293a48"
    - name: Deploy to Heroku
      uses: actions/heroku@v2
      with:
        app-name: "xlnetbot"
        heroku_api_key: "c3814a48-7319-4586-ab1d-a6a5bf293a48"
        buildpacks: heroku/python
        push-github-commit: true
